### ISSUE TITLE
`vnet_default_interface` default to 'auto'

### ISSUE THREAD

**Issue by dgeo** [freebsd/iocage#10]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- iocage 1.6
- start jail with config containng: `{ interfaces: "vnet0:bridge104", ip6_addr: "vnet0|accept_rtadv" }`
- jail is started, vnet iface is added to bridge104 but default host's interface is also added !
- Same without adding automatically hosts's default iface

`vnet_default_interface` defaults to 'auto'

I'm not sure of what has to be done with default value… some ideas ?

**Comment by bravesirrobin81** [comment]
I just fell over this today! It also happens when `ip6_addr` contains an actual address. The man page claims the default should be `none` if that's of any use. 

I changed the value for that jail(and the default) to `none` and the default interface is not added to the bridge. 


PS: Thanks @dgeo  for picking up the torch on this -- nice to see some activity after so many years. Any chance there might be an update to the port/package at some point? Happy to help with any testing/bug-fixing if needed.

**Comment by dgeo** [comment]
I think I will change default to "none", but now I'm far from keyboard ;)
Thank you for your feedback !

**Comment by dgeo** [comment]
thank you @bravesirrobin81 for your input here :)
